---
# tasks file for backend
- name: Install required packages for Caddy web server
  apt:
    update_cache: yes
    name: 
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl

- name: Download Caddy GPG key
  shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/testing/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-testing-archive-keyring.gpg

- name: Add Caddy repository to sources.list.d 
  shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/testing/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-testing.list

- name: Install Caddy
  apt:
    name: caddy
    state: present

- name: Copy Caddyfile to /etc/caddy
  ansible.builtin.copy:
    src: /home/amanda/Terraform_Assignment_3/as3-files-4640-w24-main/Caddyfile
    dest: /etc/caddy
    force: yes
  notify: Restart Caddy service

- name: Ensure /var/www/backend directory exists
  ansible.builtin.file:
    path: /var/www/backend/
    state: directory
    mode: 0775
    recurse: yes

- name: Ensure /var/log/hello-server directory exists 
  ansible.builtin.file:
    path: /var/log/hello-server/
    state: directory 
    mode: 0775
    recurse: yes

- name: Copy hello-server to /var/www/backend
  ansible.builtin.copy:
    src: /home/amanda/Terraform_Assignment_3/as3-files-4640-w24-main/hello-server
    dest: /var/www/backend

- name: Set permissions for hello-server
  ansible.builtin.file:
    path: /var/www/backend/hello-server
    mode: 0755

- name: Copy hello-server.service to /etc/systemd/system
  ansible.builtin.copy:
    src: /home/amanda/Terraform_Assignment_3/as3-files-4640-w24-main/hello-server.service
    dest: /etc/systemd/system
  notify: 
    - Reload systemd daemon
    - Start and enable hello-server.service
